PERSONAL_GOALS=12
PERSONAL_GOALS_SIZE=6
COMMON_GOALS=12
BOARD_DIMENSION=9
INPUT_SIZE=PERSONAL_GOALS+COMMON_GOALS
########################################################################################################################
COLORS_NUMBER=6
ROWS_NUMBER=6
COLUMNS_NUMBER=5
########################################################################################################################
MAX_MOVE_SIZE=3
ALL_POSSIBLE_MOVES=COLORS_NUMBER+COLORS_NUMBER*COLORS_NUMBER+COLORS_NUMBER*COLORS_NUMBER*COLORS_NUMBER
OUTPUT_SIZE=ALL_POSSIBLE_MOVES+COLUMNS_NUMBER
########################################################################################################################
FITNESS_SAME_NEIGHBOUR=0.3
FITNESS_DIFF_NEIGHBOUR=-0.1
FITNESS_FULL_VALUE=1.0
FITNESS_PG_ACHIEVED=2.0
FITNESS_PG_FAILED=-2.0